### ISSUE TITLE
prometheus_exporter.py I think the api removed some 'keys' from json

### ISSUE THREAD

**Issue by AleixoLucas42** [vinicelms/sonarqube-prometheus-exporter#12]
prometheus_exporter.py I think the api removed some 'keys' from json but Idk python to solve

Im using sonarqube version: 9.5
I Ran from master branch

docker build -t sonarqube .
docker run -e SONAR_URL='asdasd' -e SONAR_USER='asdasd' -e SONAR_PASSWORD='asdas' sonarqube

error:
Traceback (most recent call last):
  File "core/prometheus_exporter.py", line 43, in <module>
    prom.REGISTRY.register(custom_exporter)
  File "/usr/local/lib/python3.6/site-packages/prometheus_client/registry.py", line 24, in register
    names = self._get_names(collector)
  File "/usr/local/lib/python3.6/site-packages/prometheus_client/registry.py", line 64, in _get_names
    for metric in desc_func():
  File "core/prometheus_exporter.py", line 12, in collect
    projects = get_all_projects_with_metrics()
  File "/core/sonarqube_exporter.py", line 161, in get_all_projects_with_metrics
    p = Project(identifier=project['id'], key=project['key'])
KeyError: 'id'

I know my sonarqube api was working because i get some values in another aplication

**Comment by vinicelms** [comment]
Hello, @AleixoLucas42 !

Sorry for the delay to answering you. This project was freeze, but now I'm returning it.

@rmso27 fixed this problem on your pull request. I approved few minutes ago.

If you consider this topic important, please let me know. If you not, I will close this issue in some days. 

Thanks for your interest!
